-- SweetStop POS initial schema
-- Postgres/Supabase compatible

create extension if not exists pgcrypto;
create extension if not exists citext;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.access_roles (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.permissions (
  id integer generated by default as identity primary key,
  permission_key text not null unique,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role_id smallint not null references public.access_roles(id) on delete cascade,
  permission_id integer not null references public.permissions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  firstname text not null,
  lastname text not null,
  gender text,
  birthdate date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (gender is null or gender in ('MALE', 'FEMALE', 'NON_BINARY', 'PREFER_NOT_TO_SAY'))
);

create table if not exists public.accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(id) on delete cascade,
  username citext not null unique,
  contact_no text,
  email_address citext not null unique,
  access_id smallint not null references public.access_roles(id),
  password_hash text not null,
  status text not null default 'ACTIVE',
  last_active_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

create table if not exists public.branches (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text,
  timezone text not null default 'Asia/Manila',
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('ACTIVE', 'INACTIVE'))
);

create table if not exists public.promotions (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete cascade,
  name text not null,
  code text,
  description text,
  discount_type text not null,
  discount_value numeric(12, 2) not null check (discount_value > 0),
  min_subtotal numeric(12, 2) not null default 0 check (min_subtotal >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, code),
  check (discount_type in ('PERCENT', 'FIXED')),
  check (discount_type <> 'PERCENT' or discount_value <= 100),
  check (status in ('ACTIVE', 'INACTIVE')),
  check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create table if not exists public.account_branch_roles (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.accounts(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  access_id smallint not null references public.access_roles(id),
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, branch_id)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  name text not null,
  photo_url text,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  name text not null,
  sku text unique,
  description text,
  tags jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, name),
  check (jsonb_typeof(tags) = 'object')
);

create table if not exists public.branch_variant_config (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete cascade,
  variant_id uuid not null references public.product_variants(id) on delete cascade,
  price numeric(12, 2) not null check (price >= 0),
  is_applicable boolean not null default true,
  is_hidden boolean not null default false,
  manual_unavailable boolean not null default false,
  unavailable_from timestamptz,
  unavailable_to timestamptz,
  unavailable_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, variant_id),
  check (unavailable_to is null or unavailable_from is null or unavailable_to > unavailable_from)
);

create table if not exists public.branch_variant_inventory (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete cascade,
  variant_id uuid not null references public.product_variants(id) on delete cascade,
  on_hand_qty numeric(12, 3) not null default 0 check (on_hand_qty >= 0),
  reorder_level numeric(12, 3) not null default 0 check (reorder_level >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, variant_id)
);

create table if not exists public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete cascade,
  variant_id uuid not null references public.product_variants(id) on delete restrict,
  movement_type text not null,
  quantity numeric(12, 3) not null check (quantity > 0),
  reference_type text,
  reference_id uuid,
  notes text,
  created_by_account_id uuid references public.accounts(id) on delete set null,
  created_at timestamptz not null default now(),
  check (movement_type in ('IN', 'OUT', 'ADJUSTMENT'))
);

create table if not exists public.shifts (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete restrict,
  opened_by_account_id uuid not null references public.accounts(id) on delete restrict,
  closed_by_account_id uuid references public.accounts(id) on delete set null,
  opening_cash numeric(12, 2) not null default 0 check (opening_cash >= 0),
  closing_cash_expected numeric(12, 2) check (closing_cash_expected >= 0),
  closing_cash_actual numeric(12, 2) check (closing_cash_actual >= 0),
  cash_variance numeric(12, 2),
  status text not null default 'OPEN',
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('OPEN', 'CLOSED')),
  check (
    (status = 'OPEN' and closed_at is null and closed_by_account_id is null and closing_cash_actual is null)
    or
    (
      status = 'CLOSED'
      and closed_at is not null
      and closed_by_account_id is not null
      and closing_cash_expected is not null
      and closing_cash_actual is not null
    )
  )
);

create table if not exists public.sales_receipts (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete restrict,
  shift_id uuid references public.shifts(id) on delete set null,
  receipt_no text not null,
  cashier_account_id uuid not null references public.accounts(id) on delete restrict,
  promotion_id uuid references public.promotions(id) on delete set null,
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  discount_total numeric(12, 2) not null default 0 check (discount_total >= 0),
  discount_label text,
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  cash_received numeric(12, 2) not null check (cash_received >= 0),
  change_amount numeric(12, 2) not null default 0 check (change_amount >= 0),
  status text not null default 'COMPLETED',
  voided_by_account_id uuid references public.accounts(id) on delete set null,
  voided_at timestamptz,
  void_reason text,
  sold_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, receipt_no),
  check (status in ('COMPLETED', 'VOIDED')),
  check (subtotal >= discount_total),
  check (total_amount = subtotal - discount_total),
  check (cash_received >= total_amount),
  check (change_amount = cash_received - total_amount),
  check (
    (status = 'COMPLETED' and voided_at is null and voided_by_account_id is null)
    or
    (status = 'VOIDED' and voided_at is not null and voided_by_account_id is not null)
  )
);

alter table public.sales_receipts
  add column if not exists promotion_id uuid references public.promotions(id) on delete set null,
  add column if not exists discount_label text;

create table if not exists public.sales_receipt_items (
  id uuid primary key default gen_random_uuid(),
  receipt_id uuid not null references public.sales_receipts(id) on delete cascade,
  variant_id uuid not null references public.product_variants(id) on delete restrict,
  product_name_snapshot text not null,
  variant_name_snapshot text not null,
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  quantity numeric(12, 3) not null check (quantity > 0),
  discount_amount numeric(12, 2) not null default 0 check (discount_amount >= 0),
  line_total numeric(12, 2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.cash_movements (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete restrict,
  shift_id uuid references public.shifts(id) on delete set null,
  created_by_account_id uuid not null references public.accounts(id) on delete restrict,
  movement_type text not null,
  category text not null,
  amount numeric(12, 2) not null check (amount > 0),
  reference_no text,
  reason text,
  status text not null default 'POSTED',
  voided_by_account_id uuid references public.accounts(id) on delete set null,
  voided_at timestamptz,
  void_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (movement_type in ('IN', 'OUT')),
  check (status in ('POSTED', 'VOIDED')),
  check (
    (status = 'POSTED' and voided_at is null and voided_by_account_id is null)
    or
    (status = 'VOIDED' and voided_at is not null and voided_by_account_id is not null)
  )
);

create table if not exists public.daily_reports (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete restrict,
  business_date date not null,
  timezone text not null default 'Asia/Manila',
  period_start_at timestamptz not null,
  period_end_at timestamptz not null,
  generated_by_account_id uuid not null references public.accounts(id) on delete restrict,
  generated_at timestamptz not null default now(),
  status text not null default 'GENERATING',
  receipts_count integer not null default 0 check (receipts_count >= 0),
  voided_count integer not null default 0 check (voided_count >= 0),
  items_sold_qty numeric(12, 3) not null default 0 check (items_sold_qty >= 0),
  gross_sales numeric(12, 2) not null default 0 check (gross_sales >= 0),
  discount_total numeric(12, 2) not null default 0 check (discount_total >= 0),
  net_sales numeric(12, 2) not null default 0 check (net_sales >= 0),
  cash_in_total numeric(12, 2) not null default 0 check (cash_in_total >= 0),
  cash_out_total numeric(12, 2) not null default 0 check (cash_out_total >= 0),
  expected_cash_end numeric(12, 2) not null default 0 check (expected_cash_end >= 0),
  actual_cash_end numeric(12, 2) check (actual_cash_end >= 0),
  cash_variance numeric(12, 2),
  pdf_url text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, business_date),
  check (status in ('GENERATING', 'READY', 'FAILED')),
  check (period_end_at > period_start_at)
);

create table if not exists public.daily_report_product_sales (
  report_id uuid not null references public.daily_reports(id) on delete cascade,
  variant_id uuid not null references public.product_variants(id) on delete restrict,
  product_name_snapshot text not null,
  variant_name_snapshot text not null,
  qty_sold numeric(12, 3) not null default 0 check (qty_sold >= 0),
  sales_amount numeric(12, 2) not null default 0 check (sales_amount >= 0),
  primary key (report_id, variant_id)
);

create table if not exists public.daily_report_cashier_sales (
  report_id uuid not null references public.daily_reports(id) on delete cascade,
  account_id uuid not null references public.accounts(id) on delete restrict,
  cashier_name text not null,
  receipts_count integer not null default 0 check (receipts_count >= 0),
  sales_amount numeric(12, 2) not null default 0 check (sales_amount >= 0),
  primary key (report_id, account_id)
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid references public.branches(id) on delete set null,
  account_id uuid references public.accounts(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  details jsonb not null default '{}'::jsonb,
  reason text,
  created_at timestamptz not null default now(),
  check (jsonb_typeof(details) = 'object')
);

create index if not exists idx_accounts_access_id on public.accounts(access_id);
create index if not exists idx_account_branch_roles_branch_id on public.account_branch_roles(branch_id);
create index if not exists idx_promotions_branch_status on public.promotions(branch_id, status);
create index if not exists idx_products_category on public.products(category);
create index if not exists idx_product_variants_product_id on public.product_variants(product_id);
create index if not exists idx_branch_variant_config_branch_id on public.branch_variant_config(branch_id);
create index if not exists idx_branch_variant_inventory_branch_id on public.branch_variant_inventory(branch_id);
create index if not exists idx_inventory_movements_branch_variant_created_at on public.inventory_movements(branch_id, variant_id, created_at desc);
create index if not exists idx_shifts_branch_status on public.shifts(branch_id, status);
create unique index if not exists uq_shifts_open_per_branch on public.shifts(branch_id) where status = 'OPEN';
create index if not exists idx_sales_receipts_branch_sold_at on public.sales_receipts(branch_id, sold_at desc);
create index if not exists idx_sales_receipts_shift_id on public.sales_receipts(shift_id);
create index if not exists idx_sales_receipts_cashier on public.sales_receipts(cashier_account_id);
create index if not exists idx_sales_receipt_items_receipt_id on public.sales_receipt_items(receipt_id);
create index if not exists idx_sales_receipt_items_variant_id on public.sales_receipt_items(variant_id);
create index if not exists idx_cash_movements_branch_created_at on public.cash_movements(branch_id, created_at desc);
create index if not exists idx_daily_reports_branch_business_date on public.daily_reports(branch_id, business_date desc);
create index if not exists idx_audit_logs_branch_created_at on public.audit_logs(branch_id, created_at desc);

drop trigger if exists trg_access_roles_updated_at on public.access_roles;
create trigger trg_access_roles_updated_at
before update on public.access_roles
for each row execute function public.set_updated_at();

drop trigger if exists trg_permissions_updated_at on public.permissions;
create trigger trg_permissions_updated_at
before update on public.permissions
for each row execute function public.set_updated_at();

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_accounts_updated_at on public.accounts;
create trigger trg_accounts_updated_at
before update on public.accounts
for each row execute function public.set_updated_at();

drop trigger if exists trg_branches_updated_at on public.branches;
create trigger trg_branches_updated_at
before update on public.branches
for each row execute function public.set_updated_at();

drop trigger if exists trg_promotions_updated_at on public.promotions;
create trigger trg_promotions_updated_at
before update on public.promotions
for each row execute function public.set_updated_at();

drop trigger if exists trg_account_branch_roles_updated_at on public.account_branch_roles;
create trigger trg_account_branch_roles_updated_at
before update on public.account_branch_roles
for each row execute function public.set_updated_at();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists trg_product_variants_updated_at on public.product_variants;
create trigger trg_product_variants_updated_at
before update on public.product_variants
for each row execute function public.set_updated_at();

drop trigger if exists trg_branch_variant_config_updated_at on public.branch_variant_config;
create trigger trg_branch_variant_config_updated_at
before update on public.branch_variant_config
for each row execute function public.set_updated_at();

drop trigger if exists trg_branch_variant_inventory_updated_at on public.branch_variant_inventory;
create trigger trg_branch_variant_inventory_updated_at
before update on public.branch_variant_inventory
for each row execute function public.set_updated_at();

drop trigger if exists trg_shifts_updated_at on public.shifts;
create trigger trg_shifts_updated_at
before update on public.shifts
for each row execute function public.set_updated_at();

drop trigger if exists trg_sales_receipts_updated_at on public.sales_receipts;
create trigger trg_sales_receipts_updated_at
before update on public.sales_receipts
for each row execute function public.set_updated_at();

drop trigger if exists trg_cash_movements_updated_at on public.cash_movements;
create trigger trg_cash_movements_updated_at
before update on public.cash_movements
for each row execute function public.set_updated_at();

drop trigger if exists trg_daily_reports_updated_at on public.daily_reports;
create trigger trg_daily_reports_updated_at
before update on public.daily_reports
for each row execute function public.set_updated_at();

create or replace view public.branch_variant_availability_v as
select
  c.branch_id,
  c.variant_id,
  p.id as product_id,
  p.name as product_name,
  p.category as product_category,
  v.name as variant_name,
  c.price,
  c.is_applicable,
  c.is_hidden,
  c.manual_unavailable,
  c.unavailable_from,
  c.unavailable_to,
  c.unavailable_reason,
  coalesce(i.on_hand_qty, 0) as on_hand_qty,
  case
    when c.is_applicable = false then 'NOT_APPLICABLE'
    when c.is_hidden = true then 'HIDDEN'
    when c.manual_unavailable = true
      and (c.unavailable_from is null or now() >= c.unavailable_from)
      and (c.unavailable_to is null or now() < c.unavailable_to) then 'UNAVAILABLE'
    when coalesce(i.on_hand_qty, 0) <= 0 then 'OUT_OF_STOCK'
    else 'AVAILABLE'
  end as availability_status,
  case
    when c.is_applicable = true
      and c.is_hidden = false
      and not (
        c.manual_unavailable = true
        and (c.unavailable_from is null or now() >= c.unavailable_from)
        and (c.unavailable_to is null or now() < c.unavailable_to)
      )
      and coalesce(i.on_hand_qty, 0) > 0 then true
    else false
  end as is_sellable
from public.branch_variant_config c
join public.product_variants v on v.id = c.variant_id
join public.products p on p.id = v.product_id
left join public.branch_variant_inventory i
  on i.branch_id = c.branch_id
  and i.variant_id = c.variant_id;
